
      tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface-container-low": "#f2f3ff",
              "on-secondary-fixed-variant": "#004e5c",
              "error-container": "#ffdad6",
              "on-primary-container": "#eeefff",
              "surface-variant": "#dae2fd",
              "on-secondary-fixed": "#001f26",
              "surface-bright": "#faf8ff",
              "outline-variant": "#c3c6d7",
              outline: "#737686",
              background: "#faf8ff",
              "secondary-container": "#57dffe",
              "secondary-fixed-dim": "#4cd7f6",
              surface: "#faf8ff",
              "surface-container-high": "#e2e7ff",
              "primary-fixed": "#dbe1ff",
              "tertiary-fixed": "#dce2f6",
              "on-primary-fixed": "#00174b",
              "inverse-primary": "#b4c5ff",
              "on-primary-fixed-variant": "#003ea8",
              "on-tertiary-fixed-variant": "#404757",
              "on-background": "#131b2e",
              secondary: "#00687a",
              "on-secondary-container": "#006172",
              "tertiary-container": "#666d7e",
              primary: "#004ac6",
              "inverse-on-surface": "#eef0ff",
              "on-tertiary-fixed": "#151b2a",
              "surface-dim": "#d2d9f4",
              "on-surface-variant": "#434655",
              "primary-fixed-dim": "#b4c5ff",
              "surface-container": "#eaedff",
              error: "#ba1a1a",
              "surface-tint": "#0053db",
              "on-primary": "#ffffff",
              "on-tertiary": "#ffffff",
              "on-tertiary-container": "#ecf0ff",
              "primary-container": "#2563eb",
              tertiary: "#4e5565",
              "on-error": "#ffffff",
              "secondary-fixed": "#acedff",
              "inverse-surface": "#283044",
              "surface-container-highest": "#dae2fd",
              "tertiary-fixed-dim": "#c0c6da",
              "surface-container-lowest": "#ffffff",
              "on-secondary": "#ffffff",
              "on-error-container": "#93000a",
              "on-surface": "#131b2e",
            },
            borderRadius: {
              DEFAULT: "0.25rem",
              lg: "0.5rem",
              xl: "0.75rem",
              full: "9999px",
            },
            spacing: {
              "margin-tablet": "2rem",
              "space-sm": "0.75rem",
              "gutter-desktop": "1.5rem",
              "container-max-width": "1280px",
              "space-lg": "1.5rem",
              "space-4xl": "6rem",
              "space-md": "1rem",
              "margin-mobile": "1.25rem",
              "margin-desktop": "3rem",
              "space-3xl": "4rem",
              "space-xl": "2rem",
              "space-xs": "0.5rem",
              "gutter-mobile": "1rem",
              "space-2xs": "0.25rem",
              "space-2xl": "3rem",
            },
            fontFamily: {
              "code-telemetry": ["Inter"],
              "display-hero": ["Plus Jakarta Sans"],
              "headline-xl": ["Plus Jakarta Sans"],
              "body-md": ["Inter"],
              "headline-lg": ["Plus Jakarta Sans"],
              "label-badge": ["Plus Jakarta Sans"],
              "label-caps": ["Plus Jakarta Sans"],
              "display-hero-mobile": ["Plus Jakarta Sans"],
              "headline-xl-mobile": ["Plus Jakarta Sans"],
              "headline-lg-mobile": ["Plus Jakarta Sans"],
              "headline-sm": ["Plus Jakarta Sans"],
              "body-sm": ["Inter"],
              "headline-md": ["Plus Jakarta Sans"],
              "body-lg": ["Inter"],
            },
            fontSize: {
              "code-telemetry": [
                "13px",
                {
                  lineHeight: "18px",
                  letterSpacing: "0.01em",
                  fontWeight: "500",
                },
              ],
              "display-hero": [
                "56px",
                {
                  lineHeight: "64px",
                  letterSpacing: "-0.03em",
                  fontWeight: "800",
                },
              ],
              "headline-xl": [
                "40px",
                {
                  lineHeight: "48px",
                  letterSpacing: "-0.025em",
                  fontWeight: "700",
                },
              ],
              "body-md": [
                "16px",
                { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
              ],
              "headline-lg": [
                "32px",
                {
                  lineHeight: "40px",
                  letterSpacing: "-0.02em",
                  fontWeight: "700",
                },
              ],
              "label-badge": [
                "12px",
                {
                  lineHeight: "16px",
                  letterSpacing: "0.02em",
                  fontWeight: "600",
                },
              ],
              "label-caps": [
                "12px",
                {
                  lineHeight: "16px",
                  letterSpacing: "0.08em",
                  fontWeight: "700",
                },
              ],
              "display-hero-mobile": [
                "36px",
                {
                  lineHeight: "44px",
                  letterSpacing: "-0.025em",
                  fontWeight: "800",
                },
              ],
              "headline-xl-mobile": [
                "28px",
                {
                  lineHeight: "36px",
                  letterSpacing: "-0.02em",
                  fontWeight: "700",
                },
              ],
              "headline-lg-mobile": [
                "24px",
                {
                  lineHeight: "32px",
                  letterSpacing: "-0.015em",
                  fontWeight: "700",
                },
              ],
              "headline-sm": [
                "18px",
                {
                  lineHeight: "26px",
                  letterSpacing: "-0.01em",
                  fontWeight: "600",
                },
              ],
              "body-sm": [
                "14px",
                { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
              ],
              "headline-md": [
                "24px",
                {
                  lineHeight: "32px",
                  letterSpacing: "-0.015em",
                  fontWeight: "600",
                },
              ],
              "body-lg": [
                "18px",
                {
                  lineHeight: "28px",
                  letterSpacing: "-0.05em",
                  fontWeight: "400",
                },
              ],
            },
          },
        },
      };
    